services:
  postgres:
    image: postgres:16-alpine
    container_name: app_ong-postgres-1
    restart: always
    environment:
      POSTGRES_USER: gestao_ong
      POSTGRES_PASSWORD: "@Slipknot12"
      POSTGRES_DB: gestao_ong
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gestao_ong"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - proxy

  app:
    build:
      context: ./app_src
      target: runner
    container_name: app_ong-app-1
    restart: always
    volumes:
      - uploads_data:/app/public/uploads
    ports:
      - "3005:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      DATABASE_URL: postgresql://gestao_ong:%40Slipknot12@postgres:5432/gestao_ong
      NEXTAUTH_SECRET: "f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0"
      NEXTAUTH_URL: https://gestaobalance.app.br
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - proxy

volumes:
  pgdata:
  uploads_data:

networks:
  default:
  proxy:
    external:
      name: rds-pedidos_default
